plugins {
    id 'com.android.application'
}

android {
    namespace 'net.scinova.usbthing'
    compileSdkVersion 34
    //buildToolsVersion '30.0.3'


    defaultConfig {
        applicationId "net.scinova.usbthing"
        minSdkVersion 19
        targetSdkVersion 34
        versionCode 1
        versionName "0.03"

        //testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    android.applicationVariants.all { variant ->
        variant.outputs.forEach { output ->
            def outputFileName = "UsbThing-${variant.versionName}.apk"
            output.outputFileName = outputFileName
        }
    }




}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
//    implementation 'com.google.android.material:material:1.11.0' // Example dependency
}